import api from './index'

const snake = (value) => value.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
const camel = (value) => value.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase())
const convert = (value, keyFn) => Array.isArray(value)
  ? value.map((item) => convert(item, keyFn))
  : value && value.constructor === Object
    ? Object.fromEntries(Object.entries(value).map(([key, item]) => [keyFn(key), convert(item, keyFn)]))
    : value

const get = (url, params, config = {}) => api.get(url, { ...config, params: convert(params, snake) }).then((res) => convert(res, camel))
const post = (url, data) => api.post(url, convert(data, snake)).then((res) => convert(res, camel))
const put = (url, data) => api.put(url, convert(data, snake)).then((res) => convert(res, camel))

export const getPlatforms = (clientId, params = {}, config = {}) => get('/annotation-ops/platforms', { client_id: clientId || undefined, ...params }, config)
export const createPlatform = (data) => post('/annotation-ops/platforms', data)
export const updatePlatform = (id, data) => put(`/annotation-ops/platforms/${id}`, data)
export const deletePlatform = (id) => api.delete(`/annotation-ops/platforms/${id}`)
export const getAccounts = (params = {}, config = {}) => get('/annotation-ops/accounts', params, config)
export const getAccountCount = (params = {}, config = {}) => get('/annotation-ops/accounts/count', params, config)
export const createAccount = (data) => post('/annotation-ops/accounts', data)
export const batchSaveAccounts = (data) => post('/annotation-ops/accounts/batch-save', data)
export const revealAccount = (id, data = {}) => post(`/annotation-ops/accounts/${id}/reveal`, data)
export const revealAccountsBatch = (data) => post('/annotation-ops/accounts/batch-reveal', data)
const accountImportForm = (file, options) => {
  const form = new FormData()
  form.append('file', file)
  form.append('defaults_json', JSON.stringify(options.defaults || {}))
  if (options.sheetName) form.append('sheet_name', options.sheetName)
  if (options.headerRow) form.append('header_row', String(options.headerRow))
  if (options.mapping) form.append('mapping_json', JSON.stringify(options.mapping))
  return form
}
export const previewAccountImport = (file, options) => post('/annotation-ops/accounts/import/preview', accountImportForm(file, options))
export const importAccounts = (file, options) => post('/annotation-ops/accounts/import', accountImportForm(file, options))
export const getAnnotatorOccupancy = (projectId = null) => get('/annotation-ops/accounts/annotator-occupancy', { projectId: projectId || undefined })
export const updateAccount = (id, data) => put(`/annotation-ops/accounts/${id}`, data)
export const deleteAccount = (id) => api.delete(`/annotation-ops/accounts/${id}`)
export const assignAccount = (id, data) => post(`/annotation-ops/accounts/${id}/assign`, data)
export const releaseAccount = (id, data) => post(`/annotation-ops/accounts/${id}/release`, data)
export const getAccountAssignments = (id) => get(`/annotation-ops/accounts/${id}/assignments`)
export const getAccountStats = (clientId, params = {}, config = {}) => get('/annotation-ops/account-stats', { client_id: clientId || undefined, ...params }, config)
export const getPersonAccounts = (personId, params = {}) => get(`/annotation-ops/persons/${personId}/accounts`, params)
export const getAccountPersonProfile = (personId) => get(`/annotation-ops/persons/${personId}/profile`)
export const releaseAllPersonAccounts = (personId, data) => post(`/annotation-ops/persons/${personId}/release-all`, data)
export const getTrials = (projectId, params = {}, config = {}) => get('/annotation-ops/trials', { project_id: projectId || undefined, ...params }, config)
export const createTrial = (data) => post('/annotation-ops/trials', data)
export const updateTrial = (id, data) => put(`/annotation-ops/trials/${id}`, data)
export const deleteTrial = (id) => api.delete(`/annotation-ops/trials/${id}`)
export const saveAssigneeRate = (assigneeId, data) => put(`/annotation-ops/assignees/${assigneeId}/rate`, data)
export const deleteAssigneeRate = (assigneeId) => api.delete(`/annotation-ops/assignees/${assigneeId}/rate`)
export const getAnnotationWorkflow = (projectId, params = {}, config = {}) => get('/annotation-ops/workflow', { project_id: projectId || undefined, ...params }, config)
export const createAnnotationWorkflow = (projectId, data) => post(`/annotation-ops/projects/${projectId}/workflow`, data)
export const updateAnnotationWorkflow = (projectId, assigneeId, data) => put(`/annotation-ops/projects/${projectId}/workflow/${assigneeId}`, data)
export const deleteAnnotationWorkflow = (projectId, assigneeId) => api.delete(`/annotation-ops/projects/${projectId}/workflow/${assigneeId}`)
export const getStatusHistory = (projectId) => get(`/annotation-ops/projects/${projectId}/status-history`)
export const getCustomFields = (tableCode, projectId = null, includeInactive = false) => get('/annotation-ops/custom-fields', { table_code: tableCode, project_id: projectId || undefined, include_inactive: includeInactive })
export const createCustomField = (data) => post('/annotation-ops/custom-fields', data)
export const updateCustomField = (id, data) => put(`/annotation-ops/custom-fields/${id}`, data)
export const deleteCustomField = (id) => api.delete(`/annotation-ops/custom-fields/${id}`)
