import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const annotationPage = readFileSync(new URL('../src/views/project/AnnotationProjects.vue', import.meta.url), 'utf8')
const chatPanel = readFileSync(new URL('../src/components/ProjectChatPanel.vue', import.meta.url), 'utf8')
const chatApi = readFileSync(new URL('../src/api/projectChat.js', import.meta.url), 'utf8')
const notificationBell = readFileSync(new URL('../src/components/NotificationBell.vue', import.meta.url), 'utf8')

test('标注项目进度弹窗提供纯文本项目沟通页签', () => {
  assert.match(annotationPage, /class="progress-dialog-project__label">订单号<\/span>/)
  assert.match(annotationPage, /class="progress-dialog-project__label">项目名称<\/span>/)
  assert.match(annotationPage, /activeProgressProject\?\.orderNo/)
  assert.match(annotationPage, /<el-tab-pane label="进度记录" name="progress">/)
  assert.match(annotationPage, /<el-tab-pane label="项目沟通" name="chat">/)
  assert.match(annotationPage, /project-type="annotation"/)
  assert.match(annotationPage, /:text-only="true"/)
  assert.match(annotationPage, /:always-enabled="true"/)
  assert.match(annotationPage, /\scompact\s*\/>/)
})

test('纯文本模式不提交富文本或附件字段', () => {
  assert.doesNotMatch(chatPanel, /^\s{6}<template>\s*$/m)
  assert.match(chatPanel, /props\.textOnly\s*\?\s*\{\s*content:/s)
  assert.match(chatPanel, /v-if="textOnly"[\s\S]*type="textarea"/)
  assert.match(chatPanel, /v-if="!textOnly" class="composer-attachments"/)
  assert.match(chatApi, /\/project-chat\/annotation\/\$\{projectId\}/)
})

test('标注聊天提醒可以直达项目沟通页签', () => {
  assert.match(notificationBell, /includes\('project_chat'\).*query\.tab = 'chat'/)
  assert.match(annotationPage, /route\.query\.tab==='chat'/)
  assert.match(annotationPage, /openProgress\(detail,'','chat'\)/)
})

test('标注项目沟通默认收起查询筛选并使用悬浮小窗展示', () => {
  assert.match(chatPanel, /'project-chat-panel--compact': compact/)
  assert.match(chatPanel, /compact:\s*\{ type: Boolean, default: false \}/)
  assert.match(chatPanel, /collapsibleFilters:\s*\{ type: Boolean, default: false \}/)
  assert.match(chatPanel, /v-if="collapsibleFilters"[\s\S]*v-model:visible="filterPopoverVisible"[\s\S]*placement="bottom-end"/)
  assert.match(chatPanel, /查询筛选<span v-if="activeFilterCount">（\{\{ activeFilterCount \}\}）<\/span>/)
  assert.match(chatPanel, /class="chat-filter-bar chat-filter-bar--popover"/)
  assert.match(chatPanel, /<AppForm v-if="!collapsibleFilters"/)
  assert.match(annotationPage, /:collapsible-filters="true"/)
  assert.match(chatPanel, /\.project-chat-panel--compact \.chat-composer__body\s*\{[\s\S]*display:\s*flex;[\s\S]*align-items:\s*flex-end;/)
})

test('标注和笔译聊天统一支持多人提醒与私有收藏', () => {
  assert.match(chatPanel, /v-model="composer\.mentionedUserIds"/)
  assert.match(chatPanel, /\smultiple\s/)
  assert.match(chatPanel, /:multiple-limit="20"/)
  assert.match(chatPanel, /collapse-tags-tooltip/)
  assert.match(chatPanel, /messageMentions\(message\)\.slice\(0, 3\)/)
  assert.match(chatPanel, /只看收藏/)
  assert.match(chatPanel, /favorites_only: filters\.favoritesOnly/)
  assert.match(chatPanel, /收藏（仅自己可见）/)
  assert.match(chatApi, /put\(`\/project-chat\/messages\/\$\{messageId\}\/favorite`\)/)
  assert.match(chatApi, /delete\(`\/project-chat\/messages\/\$\{messageId\}\/favorite`\)/)
})

test('标注沟通消息支持多选后带入补充进度且不会影响笔译默认行为', () => {
  assert.match(chatPanel, /canAddToProgress:\s*\{ type: Boolean, default: false \}/)
  assert.match(chatPanel, /defineEmits\(\['add-to-progress'\]\)/)
  assert.match(chatPanel, /progressSelectionMode/)
  assert.match(chatPanel, /批量选择/)
  assert.match(chatPanel, /class="chat-batch-action-bar"/)
  assert.match(chatPanel, /已选 \{\{ selectedProgressMessages\.length \}\} 条/)
  assert.match(chatPanel, /预计 \{\{ selectedProgressCharacterCount \}\} \/ 10000 字/)
  assert.match(chatPanel, /Shift \+ 点击可连续选择/)
  assert.match(chatPanel, /全选本页/)
  assert.match(chatPanel, /handleProgressMessageCardClick/)
  assert.match(chatPanel, /event\.shiftKey && lastSelectedProgressMessageId\.value/)
  assert.match(chatPanel, /:disabled="!selectedProgressMessages\.length \|\| selectedProgressCharacterCount > 10000"/)
  assert.match(chatPanel, /emit\('add-to-progress', \[\.\.\.selectedProgressMessages\.value\]\)/)
  assert.match(annotationPage, /:can-add-to-progress="canWrite"/)
  assert.match(annotationPage, /@add-to-progress="handleChatMessageToProgress"/)
})

test('多条沟通消息按发送人整理后预填补充进度并保留两条进度操作路线', () => {
  assert.match(annotationPage, /const handleChatMessageToProgress=async\(messages\)=>/)
  assert.match(annotationPage, /sourceMessages\.map\(\(\{message,content:messageContent\}\)=>`【\$\{message\?\.senderName\|\|'未知用户'\}】\\n\$\{messageContent\}`\)/)
  assert.match(annotationPage, /content\.length>10000/)
  assert.match(annotationPage, /messageCount:sourceMessages\.length/)
  assert.match(annotationPage, /senderSummary:senderNames\.join\('、'\)/)
  assert.match(annotationPage, /statusEntryMode\.value='progress'/)
  assert.match(annotationPage, /projectStatus:activeProgressProject\.value\?\.projectStatus\|\|''/)
  assert.match(annotationPage, /effectiveOn:localDateTimeValue\(effectiveDate\)/)
  assert.match(annotationPage, /changeNote:content/)
  assert.match(annotationPage, /具体进度中已有未保存内容/)
  assert.match(annotationPage, /progressDialogTab\.value='progress'/)
  assert.match(annotationPage, /已从项目沟通带入/)
  assert.match(annotationPage, /:maxlength="statusEntryMode === 'progress' \? 10000 : 500"/)
  assert.match(annotationPage, /progressDraftSource\.value=null;statusForm\.projectStatus=mode==='progress'[\s\S]*statusForm\.effectiveOn=localDateTimeValue\(\)/)
  assert.match(annotationPage, /progressOnly=statusEntryMode\.value==='progress'/)
})

test('消息右键使用微信式操作菜单、高亮当前消息并支持多选和精确摘录', () => {
  assert.match(chatPanel, /@contextmenu="handleMessageContextMenu\(\$event, message\)"/)
  assert.match(chatPanel, /'chat-message-card--context-active': progressTextMenu\.visible/)
  assert.match(chatPanel, /\.chat-message-card--context-active\s*\{[\s\S]*border-color: var\(--el-color-primary\);/)
  assert.match(chatPanel, /添加选中内容为进度/)
  assert.match(chatPanel, /'添加为进度'/)
  assert.match(chatPanel, /<CirclePlus \/>/)
  assert.match(chatPanel, /<CopyDocument \/>/)
  assert.match(chatPanel, /class="chat-selection-menu__divider" role="separator"/)
  assert.match(chatPanel, /handleContextFavoriteToggle/)
  assert.match(chatPanel, /progressTextMenu\.message\?\.isFavorited \? '取消收藏' : '收藏'/)
  assert.match(chatPanel, /<span>多选<\/span>/)
  assert.match(chatPanel, /handleProgressMessageSelection\(message, true\)/)
  assert.match(chatPanel, /event\.stopImmediatePropagation\(\)/)
  assert.match(chatPanel, /window\.addEventListener\('keydown', handleProgressTextMenuKeydown, true\)/)
  assert.match(chatPanel, /const handleMessageContextMenu = \(event, message\) =>/)
  assert.match(chatPanel, /contentElement\.contains\(range\.startContainer\)/)
  assert.match(chatPanel, /event\.preventDefault\(\)/)
  assert.match(chatPanel, /content: progressTextMenu\.text/)
  assert.match(chatPanel, /copyTextToClipboard\(progressTextMenu\.text\)/)
})
